# Generated by Django 5.0.4 on 2024-05-06 00:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('deadline', models.DateTimeField(default=datetime.datetime(2024, 5, 6, 0, 50, 54, 818245, tzinfo=datetime.timezone.utc))),
                ('time_limit', models.TimeField()),
                ('uploader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('question', models.TextField(blank=True)),
                ('option_A', models.TextField(blank=True)),
                ('option_B', models.TextField(blank=True)),
                ('option_C', models.TextField(blank=True)),
                ('option_D', models.TextField(blank=True)),
                ('option_E', models.TextField(blank=True)),
                ('answer', models.TextField()),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.quizz')),
            ],
        ),
    ]
