# Generated by Django 5.0.4 on 2024-05-06 04:18

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='type',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 4, 18, 38, 123343, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg', 'pdf', 'word', 'ppt', 'excel'])])),
                ('upload_date', models.DateTimeField(default=datetime.datetime(2024, 5, 6, 4, 18, 38, 123343, tzinfo=datetime.timezone.utc))),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
