# Generated by Django 5.0.4 on 2024-05-06 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_questions_takers_alter_lesson_upload_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 5, 32, 37, 616639, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='questions',
            name='takers',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='deadline',
            field=models.DateField(),
        ),
    ]
