# Generated by Django 5.0.4 on 2024-05-06 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_lesson_upload_date_alter_questions_takers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 5, 36, 47, 514081, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='time_limit',
            field=models.IntegerField(),
        ),
    ]
