# Generated by Django 5.0.4 on 2024-05-06 12:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_questions_type_alter_lesson_upload_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizz',
            name='uploader',
        ),
        migrations.RemoveField(
            model_name='score',
            name='is_take',
        ),
        migrations.AddField(
            model_name='quizz',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizz',
            name='user_take',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usertaker', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 12, 19, 51, 655301, tzinfo=datetime.timezone.utc)),
        ),
    ]
