# Generated by Django 5.0.4 on 2024-05-06 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_quizz_uploader_remove_score_is_take_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 12, 20, 43, 399416, tzinfo=datetime.timezone.utc)),
        ),
    ]
