# Generated by Django 5.0.4 on 2024-05-06 12:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_lesson_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 12, 24, 47, 274231, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='questions',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.quizz'),
        ),
    ]
