# Generated by Django 5.0.4 on 2024-05-07 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_lesson_upload_date_forum_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizz',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='time_limit',
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 1, 15, 44, 993862, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forum',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 1, 15, 44, 993862, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 1, 15, 44, 993862, tzinfo=datetime.timezone.utc)),
        ),
    ]
