# Generated by Django 5.0.4 on 2024-05-07 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_quizz_deadline_remove_quizz_time_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='option_A',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option_B',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option_C',
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 3, 48, 57, 307858, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forum',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 3, 48, 57, 307858, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 3, 48, 57, 307858, tzinfo=datetime.timezone.utc)),
        ),
    ]
