# Generated by Django 5.0.4 on 2024-05-07 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_questions_option_a_remove_questions_option_b_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizz',
            name='user_take',
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 10, 35, 54, 730748, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forum',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 10, 35, 54, 730748, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 10, 35, 54, 730748, tzinfo=datetime.timezone.utc)),
        ),
    ]
